version: "3.9"
services:

  database_postgres:
    image: "postgres:15-alpine"
    hostname: database_postgres
    restart: unless-stopped
    container_name: database_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - doesitwork

  rabbitmq:
    hostname: rabbitmq
    restart: unless-stopped
    container_name: messagebroker
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_PLUGINS=value
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - doesitwork

networks:
  doesitwork:
    name: doesitwork_network
